# Generated by Django 4.1.3 on 2022-11-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBTest',
            fields=[
                ('test', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
